[application]

[web.app]

# HTML title tag content
title = "Cyber Vault"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap"
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
